# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: Deploy to DigitalOcean
            script:
              - ssh $SSH_FULL 'cd ../var/www/cenfit-backend && git pull origin master && php artisan migrate:fresh --seed'
            caches:
              - composer
